spring:
  cloud:
    gateway:
      routes:
#      - id: test_route
#        uri: https://www.baidu.com
#        predicates:
#        - Query=url,baidu
#
#      - id: qq_route
#        uri: https://www.qq.com
#        predicates:
#        - Query=url,qq
      
      - id: product_route
        uri: lb://fishmall-product
        predicates:
        - Path=/api/product/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: third_party_route
        uri: lb://fishmall-third-party
        predicates:
          - Path=/api/thirdparty/**
        filters:
          - RewritePath=/api/thirdparty/(?<segment>.*), /$\{segment}

      - id: member_route
        uri: lb://fishmall-member
        predicates:
          - Path=/api/member/**
        filters:
          - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: ware_route
        uri: lb://fishmall-ware
        predicates:
          - Path=/api/ware/**
        filters:
          - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: admin_route
        uri: lb://renren-fast
        predicates:
        - Path=/api/**
        filters:
        - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}

      - id: fishmall_host_route
        uri: lb://fishmall-product
        predicates:
          - Host=**.fishmall.com

# 前端项目. /api        
# GatewayFilter -> RewirtePath GatewayFilter Facotry