spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/fishmall_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: fishmall-ware
mybatis-plus:
  mapper-location: classpath*:/mapper/**/*.xml
  global-config:
      db-confg:
        id-type: auto
server:
  port: 11000